services:
  - type: web
    name: boss-worker-platform
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        value: "sqlite:///db.sqlite3"
